# Project
version=26.1.2-1.0.1

# Common
backstube_version=26.1.2-0.1.3

# Mod options
mod_name=Backstube Music
mod_author=jahirtrap
mod_id=backstubemusic
mod_license=All Rights Reserved
mod_description=Official music disc pack for Backstube
mod_url=https://www.curseforge.com/minecraft/mc-mods/backstube-music
mod_issues=https://github.com/jahirxtrap/backstube/issues